[project]
name = "jobanalyzer"
version = "0.1.0"
description = "A tool for analyzing recruitment software"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.8",
    "ruff>=0.9.3",
]
